"""Regenerate src/fplot_cmap.f90 from matplotlib's colormaps.

The Fortran library has no way to evaluate matplotlib's colormap definitions,
so the tables are sampled here and interpolated at run time. Run this if a
colormap is added or the anchor count changes:

    pixi run python tools/gen_cmap.py
"""

from pathlib import Path

import matplotlib

NAMES = ["viridis", "plasma", "inferno", "magma", "gray", "coolwarm"]
NA = 33
OUT = Path(__file__).resolve().parent.parent / "src" / "fplot_cmap.f90"


def table(name: str) -> list[str]:
    m = matplotlib.colormaps[name]
    vals: list[int] = []
    for i in range(NA):
        r, g, b, _ = m(i / (NA - 1))
        vals += [round(r * 255), round(g * 255), round(b * 255)]
    rows, line = [], []
    for v in vals:
        line.append(f"{v:4d}")
        if len(line) == 12:
            rows.append(", ".join(line))
            line = []
    if line:
        rows.append(", ".join(line))
    return rows


HEADER = f"""! fplot_cmap — matplotlib colormaps for the image, contour and scatter kinds.
!
! Generated by tools/gen_cmap.py; do not edit by hand. Each map is {NA} evenly
! spaced anchors sampled from matplotlib and linearly interpolated in between,
! which reproduces the originals to within three levels out of 255.
module fplot_cmap
    use fplot_style, only: dp
    implicit none
    private

    public :: CMAP_VIRIDIS, CMAP_PLASMA, CMAP_INFERNO, CMAP_MAGMA
    public :: CMAP_GRAY, CMAP_COOLWARM
    public :: cmap_from_str, cmap_color, cmap_rgb

    integer, parameter, public :: CMAP_N_ANCHOR = {NA}

    integer, parameter :: CMAP_VIRIDIS = 0
    integer, parameter :: CMAP_PLASMA = 1
    integer, parameter :: CMAP_INFERNO = 2
    integer, parameter :: CMAP_MAGMA = 3
    integer, parameter :: CMAP_GRAY = 4
    integer, parameter :: CMAP_COOLWARM = 5

"""

REST = '''contains

    ! Unknown names fall back to viridis, matplotlib's default.
    pure function cmap_from_str(name) result(id)
        character(len=*), intent(in) :: name
        integer :: id
        select case (trim(name))
        case ("plasma")
            id = CMAP_PLASMA
        case ("inferno")
            id = CMAP_INFERNO
        case ("magma")
            id = CMAP_MAGMA
        case ("gray", "grey")
            id = CMAP_GRAY
        case ("coolwarm", "bwr")
            id = CMAP_COOLWARM
        case default
            id = CMAP_VIRIDIS
        end select
    end function cmap_from_str

    ! Colour at position t in [0, 1], linearly interpolated between anchors.
    pure subroutine cmap_rgb(id, t, r, g, b)
        integer, intent(in) :: id
        real(dp), intent(in) :: t
        integer, intent(out) :: r, g, b
        real(dp) :: u, f
        integer :: i0, i1

        u = t
        ! A NaN would otherwise propagate into the index arithmetic below.
        if (u /= u) u = 0.0_dp
        u = max(0.0_dp, min(1.0_dp, u)) * real(CMAP_N_ANCHOR - 1, dp)
        i0 = int(u)
        if (i0 > CMAP_N_ANCHOR - 2) i0 = CMAP_N_ANCHOR - 2
        i1 = i0 + 1
        f = u - real(i0, dp)

        r = lerp(anchor(id, 3 * i0 + 1), anchor(id, 3 * i1 + 1), f)
        g = lerp(anchor(id, 3 * i0 + 2), anchor(id, 3 * i1 + 2), f)
        b = lerp(anchor(id, 3 * i0 + 3), anchor(id, 3 * i1 + 3), f)
    end subroutine cmap_rgb

    pure function cmap_color(id, t) result(hex)
        integer, intent(in) :: id
        real(dp), intent(in) :: t
        character(len=7) :: hex
        integer :: r, g, b
        call cmap_rgb(id, t, r, g, b)
        hex = "#" // hex2(r) // hex2(g) // hex2(b)
    end function cmap_color

    pure function anchor(id, k) result(v)
        integer, intent(in) :: id, k
        integer :: v
        select case (id)
        case (CMAP_PLASMA)
            v = PLASMA_D(k)
        case (CMAP_INFERNO)
            v = INFERNO_D(k)
        case (CMAP_MAGMA)
            v = MAGMA_D(k)
        case (CMAP_GRAY)
            v = GRAY_D(k)
        case (CMAP_COOLWARM)
            v = COOLWARM_D(k)
        case default
            v = VIRIDIS_D(k)
        end select
    end function anchor

    pure function lerp(a, b, f) result(v)
        integer, intent(in) :: a, b
        real(dp), intent(in) :: f
        integer :: v
        v = nint(real(a, dp) + f * real(b - a, dp))
        v = max(0, min(255, v))
    end function lerp

    pure function hex2(v) result(s)
        integer, intent(in) :: v
        character(len=2) :: s
        character(len=16), parameter :: D = "0123456789abcdef"
        integer :: w
        w = max(0, min(255, v))
        s(1:1) = D(w / 16 + 1:w / 16 + 1)
        s(2:2) = D(modulo(w, 16) + 1:modulo(w, 16) + 1)
    end function hex2

end module fplot_cmap
'''


def main() -> None:
    body = ""
    for name in NAMES:
        rows = table(name)
        body += f"    integer, parameter :: {name.upper()}_D(3 * CMAP_N_ANCHOR) = [ &\n"
        for j, r in enumerate(rows):
            last = j == len(rows) - 1
            body += f"        {r}{']' if last else ', &'}\n"
        body += "\n"
    OUT.write_text(HEADER + body + REST, encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
