! fplot_cmap — matplotlib colormaps for the image, contour and scatter kinds.
!
! Generated by tools/gen_cmap.py; do not edit by hand. Each map is 33 evenly
! spaced anchors sampled from matplotlib and linearly interpolated in between,
! which reproduces the originals to within three levels out of 255.
module fplot_cmap
    use fplot_style, only: dp
    implicit none
    private

    public :: CMAP_VIRIDIS, CMAP_PLASMA, CMAP_INFERNO, CMAP_MAGMA
    public :: CMAP_GRAY, CMAP_COOLWARM
    public :: cmap_from_str, cmap_color, cmap_rgb

    integer, parameter, public :: CMAP_N_ANCHOR = 33

    integer, parameter :: CMAP_VIRIDIS = 0
    integer, parameter :: CMAP_PLASMA = 1
    integer, parameter :: CMAP_INFERNO = 2
    integer, parameter :: CMAP_MAGMA = 3
    integer, parameter :: CMAP_GRAY = 4
    integer, parameter :: CMAP_COOLWARM = 5

    integer, parameter :: VIRIDIS_D(3 * CMAP_N_ANCHOR) = [ &
          68,    1,   84,   71,   13,   96,   72,   24,  106,   72,   35,  116, &
          71,   45,  123,   69,   55,  129,   66,   64,  134,   62,   73,  137, &
          59,   82,  139,   55,   91,  141,   51,   99,  141,   47,  107,  142, &
          44,  114,  142,   41,  122,  142,   38,  130,  142,   35,  137,  142, &
          33,  145,  140,   31,  152,  139,   31,  160,  136,   34,  167,  133, &
          40,  174,  128,   50,  182,  122,   63,  188,  115,   78,  195,  107, &
          94,  201,   98,  112,  207,   87,  132,  212,   75,  152,  216,   62, &
         173,  220,   48,  194,  223,   35,  216,  226,   25,  236,  229,   27, &
         253,  231,   37]

    integer, parameter :: PLASMA_D(3 * CMAP_N_ANCHOR) = [ &
          13,    8,  135,   34,    6,  144,   49,    5,  151,   63,    4,  156, &
          76,    2,  161,   89,    1,  165,  102,    0,  167,  114,    1,  168, &
         126,    3,  168,  138,    9,  165,  149,   17,  161,  160,   26,  156, &
         170,   35,  149,  179,   44,  142,  188,   53,  135,  196,   62,  127, &
         204,   71,  120,  211,   81,  113,  218,   90,  106,  224,   99,   99, &
         230,  108,   92,  235,  118,   85,  240,  128,   78,  245,  139,   71, &
         248,  149,   64,  251,  161,   57,  253,  172,   51,  254,  184,   44, &
         253,  197,   39,  252,  210,   37,  248,  223,   37,  244,  237,   39, &
         240,  249,   33]

    integer, parameter :: INFERNO_D(3 * CMAP_N_ANCHOR) = [ &
           0,    0,    4,    4,    3,   18,   11,    7,   36,   21,   11,   55, &
          33,   12,   74,   47,   10,   91,   61,    9,  101,   74,   12,  107, &
          87,   16,  110,  100,   21,  110,  113,   25,  110,  125,   30,  109, &
         138,   34,  106,  151,   39,  102,  163,   44,   97,  176,   49,   91, &
         188,   55,   84,  199,   62,   76,  210,   70,   68,  219,   80,   59, &
         228,   90,   49,  235,  102,   40,  241,  115,   29,  246,  128,   19, &
         249,  142,    9,  251,  157,    7,  252,  172,   17,  251,  188,   33, &
         249,  203,   53,  245,  219,   76,  242,  234,  105,  243,  246,  138, &
         252,  255,  164]

    integer, parameter :: MAGMA_D(3 * CMAP_N_ANCHOR) = [ &
           0,    0,    4,    3,    3,   18,   10,    8,   34,   19,   13,   52, &
          29,   17,   71,   41,   17,   90,   54,   16,  107,   68,   15,  118, &
          81,   18,  124,   93,   23,  127,  106,   28,  129,  118,   33,  129, &
         131,   38,  129,  144,   42,  129,  156,   46,  127,  170,   51,  125, &
         183,   55,  121,  196,   60,  117,  208,   65,  111,  220,   72,  105, &
         231,   82,   99,  239,   93,   94,  245,  107,   92,  249,  121,   93, &
         252,  137,   97,  253,  152,  105,  254,  167,  114,  254,  182,  124, &
         254,  196,  136,  254,  211,  149,  253,  226,  163,  252,  240,  178, &
         252,  253,  191]

    integer, parameter :: GRAY_D(3 * CMAP_N_ANCHOR) = [ &
           0,    0,    0,    8,    8,    8,   16,   16,   16,   24,   24,   24, &
          32,   32,   32,   40,   40,   40,   48,   48,   48,   56,   56,   56, &
          64,   64,   64,   72,   72,   72,   80,   80,   80,   88,   88,   88, &
          96,   96,   96,  104,  104,  104,  112,  112,  112,  120,  120,  120, &
         128,  128,  128,  136,  136,  136,  144,  144,  144,  152,  152,  152, &
         160,  160,  160,  168,  168,  168,  176,  176,  176,  184,  184,  184, &
         192,  192,  192,  200,  200,  200,  208,  208,  208,  216,  216,  216, &
         224,  224,  224,  232,  232,  232,  240,  240,  240,  248,  248,  248, &
         255,  255,  255]

    integer, parameter :: COOLWARM_D(3 * CMAP_N_ANCHOR) = [ &
          59,   76,  192,   68,   90,  204,   78,  104,  216,   88,  117,  225, &
          98,  130,  234,  108,  143,  241,  119,  154,  247,  130,  166,  251, &
         141,  176,  254,  152,  185,  255,  163,  194,  254,  174,  201,  252, &
         185,  208,  249,  195,  213,  244,  204,  217,  237,  213,  219,  229, &
         221,  220,  220,  229,  216,  209,  236,  211,  197,  241,  204,  184, &
         245,  196,  172,  247,  186,  159,  247,  176,  147,  246,  165,  134, &
         244,  152,  122,  240,  139,  110,  235,  125,   98,  228,  110,   86, &
         221,   95,   75,  212,   78,   65,  202,   59,   55,  190,   36,   46, &
         180,    4,   38]

contains

    ! Unknown names fall back to viridis, matplotlib's default.
    pure function cmap_from_str(name) result(id)
        character(len=*), intent(in) :: name
        integer :: id
        select case (trim(name))
        case ("plasma")
            id = CMAP_PLASMA
        case ("inferno")
            id = CMAP_INFERNO
        case ("magma")
            id = CMAP_MAGMA
        case ("gray", "grey")
            id = CMAP_GRAY
        case ("coolwarm", "bwr")
            id = CMAP_COOLWARM
        case default
            id = CMAP_VIRIDIS
        end select
    end function cmap_from_str

    ! Colour at position t in [0, 1], linearly interpolated between anchors.
    pure subroutine cmap_rgb(id, t, r, g, b)
        integer, intent(in) :: id
        real(dp), intent(in) :: t
        integer, intent(out) :: r, g, b
        real(dp) :: u, f
        integer :: i0, i1

        u = t
        ! A NaN would otherwise propagate into the index arithmetic below.
        if (u /= u) u = 0.0_dp
        u = max(0.0_dp, min(1.0_dp, u)) * real(CMAP_N_ANCHOR - 1, dp)
        i0 = int(u)
        if (i0 > CMAP_N_ANCHOR - 2) i0 = CMAP_N_ANCHOR - 2
        i1 = i0 + 1
        f = u - real(i0, dp)

        r = lerp(anchor(id, 3 * i0 + 1), anchor(id, 3 * i1 + 1), f)
        g = lerp(anchor(id, 3 * i0 + 2), anchor(id, 3 * i1 + 2), f)
        b = lerp(anchor(id, 3 * i0 + 3), anchor(id, 3 * i1 + 3), f)
    end subroutine cmap_rgb

    pure function cmap_color(id, t) result(hex)
        integer, intent(in) :: id
        real(dp), intent(in) :: t
        character(len=7) :: hex
        integer :: r, g, b
        call cmap_rgb(id, t, r, g, b)
        hex = "#" // hex2(r) // hex2(g) // hex2(b)
    end function cmap_color

    pure function anchor(id, k) result(v)
        integer, intent(in) :: id, k
        integer :: v
        select case (id)
        case (CMAP_PLASMA)
            v = PLASMA_D(k)
        case (CMAP_INFERNO)
            v = INFERNO_D(k)
        case (CMAP_MAGMA)
            v = MAGMA_D(k)
        case (CMAP_GRAY)
            v = GRAY_D(k)
        case (CMAP_COOLWARM)
            v = COOLWARM_D(k)
        case default
            v = VIRIDIS_D(k)
        end select
    end function anchor

    pure function lerp(a, b, f) result(v)
        integer, intent(in) :: a, b
        real(dp), intent(in) :: f
        integer :: v
        v = nint(real(a, dp) + f * real(b - a, dp))
        v = max(0, min(255, v))
    end function lerp

    pure function hex2(v) result(s)
        integer, intent(in) :: v
        character(len=2) :: s
        character(len=16), parameter :: D = "0123456789abcdef"
        integer :: w
        w = max(0, min(255, v))
        s(1:1) = D(w / 16 + 1:w / 16 + 1)
        s(2:2) = D(modulo(w, 16) + 1:modulo(w, 16) + 1)
    end function hex2

end module fplot_cmap
